name: Native Tests

on:
  workflow_dispatch:
  push:
    tags: [ v** ]

jobs:
  test-native:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        docker-img:
          - docker.io/arangodb/enterprise:3.11.0
        topology:
          - single
        java-version:
          - 21
        module:
          - driver
          - integration-tests

    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: ${{matrix.java-version}}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          components: 'native-image,js'
      - name: Start Database
        run: ./docker/start_db.sh
        env:
          ARANGO_LICENSE_KEY: ${{ secrets.ARANGO_LICENSE_KEY }}
          STARTER_MODE: ${{matrix.topology}}
          DOCKER_IMAGE: ${{matrix.docker-img}}
      - name: Info
        run: mvn -version
      - name: Install
        run: mvn --no-transfer-progress install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true
      - name: Test Native
        working-directory: ${{matrix.module}}
        run: mvn --no-transfer-progress -Pnative test

  test-native-ssl:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        docker-img:
          - docker.io/arangodb/enterprise:3.11.0
        topology:
          - single
        java-version:
          - 21
        module:
          - driver
          - integration-tests

    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: ${{matrix.java-version}}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          components: 'native-image,js'
      - name: Start Database
        run: ./docker/start_db.sh
        env:
          ARANGO_LICENSE_KEY: ${{ secrets.ARANGO_LICENSE_KEY }}
          STARTER_MODE: ${{matrix.topology}}
          DOCKER_IMAGE: ${{matrix.docker-img}}
          SSL: true
      - name: Info
        run: mvn -version
      - name: Install
        run: mvn --no-transfer-progress install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true
      - name: Test Native
        working-directory: ${{matrix.module}}
        run: mvn --no-transfer-progress -Pnative -Dgroups=ssl -DSslTest=true test
